### ISSUE TITLE
Paradas en la terminal de Docker

### ISSUE THREAD

**Issue by jualopmun** [DinossoLatte/egc-cabinas#1]
Muchas veces se para la maquina de consola de Docker.

**Comment by NachoAlesLopez** [comment]
Creo que te refieres a que el contenedor de MariaDB se cierra con código de error 0. ¿Verdad?. Para solucionar ese error debes asignarle los permisos a la carpeta de MariaDB, que en nuestro caso es "mariadb_data". Esto se debe a que al clonar el repositorios, coge los permisos del usuario que hace el clone y por lo tanto se asigna incorrectamente los permisos.

Ejecuta los siguientes comandos:
`sudo chown root -R mariadb_data`
`sudo chgrp root -R mariadb_data`
`sudo chmod 666 -R mariadb_data`
