### ISSUE TITLE
Error de persmisos en la BD

### ISSUE THREAD

**Issue by jualopmun** [DinossoLatte/egc-cabinas#2]
Al hacer Docker-compose, salta un error de permiso en la base de datos que no deja iniciar el entorno en localhost.
![image](https://user-images.githubusercontent.com/29895191/32994447-d553734a-cd67-11e7-960c-14166117b5f4.png)
![image](https://user-images.githubusercontent.com/29895191/32994450-db46b9a6-cd67-11e7-8b58-6fce7729b7ea.png)

**Comment by NachoAlesLopez** [comment]
Este error es el mismo que el #1. Marco como duplicado y comprueba que poniendo los comandos que se ponen en el comentario se soluciona.
