### ISSUE TITLE
Error al iniciar Docker for Windows

### ISSUE THREAD

**Issue by jualopmun** [DinossoLatte/egc-cabinas#3]
Se produce un error a ejecutar Docker for Windows
![image](https://user-images.githubusercontent.com/29895191/32994461-f70b8022-cd67-11e7-9c4a-b058bdd1f913.png)

**Comment by NachoAlesLopez** [comment]
Puede que tenga que ver con este error: https://forums.docker.com/t/erroractionpreference/10047/7

Aparentemente, si tienes menos de unos 4 o 5 gb de memoria RAM te falla porque está configurado a que tenga 2 gb.
